// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdxycnpvhuazofdsccrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkeHljbnB2aHVhem9mZHNjY3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzI5NTIsImV4cCI6MjA2OTkwODk1Mn0.rksmNSe7vygkHkDbkzSF92D4prnZC_fSwBGv3eHFdJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});